### ISSUE TITLE
exog contains inf or nans

### ISSUE THREAD

**Issue by Edwardp17** [dafiti/causalimpact#20]
Getting "exog contains inf or nans" error after running ci = CausalImpact(data, pre_period, post_period).

Works if I change the underlying script (data.pyc) from:
if not np.isfinite(ptp_).all():
--> 133                 raise MissingDataError('exog contains inf or nans')

to

if not np.isfinite(ptp_).all().all():
--> 133                 raise MissingDataError('exog contains inf or nans')

**Comment by WillianFuks** [comment]
Hi @Edwardp17 , tnx for reporting!

As I saw you just closed I'd like to confirm if you still see the error or if you found a fix (in case there was a bug please let us know and we prepare a fix :) )

**Comment by Edwardp17** [comment]
Hey Willian,

Sorry for the issue! It was a transient error that somehow went away after
trying for a few executions.

I am however getting another error that I haven’t been able to debug yet -
after trying to run ci.plot I am receiving “Cannot add integral value to
Timestamp without freq”. I think this is because I had a date column that I
then set as an index, where as in your example you create a date range with
periods which maybe sets a frequency. Would be great to note this in the
getting started notebook for future users! I’ll let you know if my fix
works (I’ll create a date range and set it as the index).

**Comment by Edwardp17** [comment]
Hi still having this issue. My solution did not fix.

**Comment by Edwardp17** [comment]
Hey,

Sorry for all the emails - I fixed my problem and created an issue in the
github with my fix.

However, I am seeing different results than I did with the R package, using
the same data.
