### ISSUE TITLE
Cannot add integral value to Timestamp without freq.

### ISSUE THREAD

**Issue by Edwardp17** [dafiti/causalimpact#21]
Hi,

This issue is caused when I run CausalImpact.plot(). When giving the original dataframe an index by setting it equal to a pd.date_range, the user creates a date range index with a freq. Somehow CausalImpac.inferences loses that freq during its construction. This creates an error when plotting in this line of code (line 64 in plot.py) 'ax.axvline(inferences.index[intervention_idx] - 1, c='k', linestyle='--',. The index for inferences needs to have a freq otherwise it will be trying to subtract 1 from a pandas timestamp that doesnt have a freq, which will raise an error.

I fixed this error by putting  self.inferences.index = self.data.index in the inferences.py on line 327. It seems to work now. I hope I'm not messing anything up by doing this!

**Comment by WillianFuks** [comment]
Hi @Edwardp17 , thx for finding that. Do you have a code sample you used to find this error? I'm not quite sure how to reproduce it here. It seems though to be related to a dataframe with date index but without freq being able to be defined which raises this issue. Maybe this should be treated right at the instantiation step.

**Comment by Edwardp17** [comment]
The error first occurred while using my own data - but then I replicated
your getting_started notebook exactly and had the error raised while
running ci.plot(). I agree, my fix is temporary and probably isn't the best
way to handle this, but it did take care of the issue. I would imagine that
it would be more flexible/scalable to require the user to initiate a date
index with a freq (as opposed to simply setting a column with dates in it
as the index).

**Comment by WillianFuks** [comment]
Hi @Edwardp17 ,

Just sent to master a fix for this issue. Thanks once again for reporting this, we had indeed a bug in our plotting function (now it's been covered with unittests as well).

Please let us know if it works for you now :). 

Soon we'll be sending this new version to PyPI as well.
