### ISSUE TITLE
Summary nitpick: "CI interval" is redundant

### ISSUE THREAD

**Issue by yanirs** [dafiti/causalimpact#23]
The generated summary mentions _CI interval_ a few times, but since _CI_ means _confidence interval_, this reads as _confidence interval interval_. I think it'd be better to say _confidence interval_, as _CI_ is also used as an abbreviation of _causal impact_.

**Comment by WillianFuks** [comment]
Hi @yanirs ,

You are totally right! Thanks for finding this, just now realized this mistake.

Will fix it soon enough :)!
