### ISSUE TITLE
Suggestion: Make model evaluation easier

### ISSUE THREAD

**Issue by yanirs** [dafiti/causalimpact#24]
As it's often possible to gather more relevant predictor series and improve model fit, it'd be nice to include a method that provides a model score with a confidence interval.

In a recent analysis, I calculated the pre-intervention mean (absolute) error like this:
```python
    impact = CausalImpact(...)
    pre_period_point_effects = impact.inferences.iloc[1:].loc[:pre_period_end][
        ['point_effects', 'point_effects_lower', 'point_effects_upper']
    ]
    pre_period_maes = pre_period_point_effects.abs().mean().round(2)
    pre_period_mean_errors = pre_period_point_effects.mean().round(2)
    print(f"Pre-period mean absolute error: {pre_period_maes['point_effects']} "
          f"(max confidence interval: {pre_period_maes.max()})")
    print(f"Pre-period mean error: {pre_period_mean_errors['point_effects']} "
          f"(confidence interval: {list(pre_period_mean_errors.iloc[1:])})")
```
I only used the MAE for model evaluation, but I'm pretty sure this can be done more rigorously. :slightly_smiling_face:

**Comment by WillianFuks** [comment]
Hello @yanirs ,

If I understood it correctly, you want some reliable way to measure how good the model could fit the data is that right?

If so, `statsmodels` already offers different statistical measures for computing goodness of fitness for the fitted model. You can access its results with:

    impact.trained_model.summary()

Which results in something like (this is using the data as created in the README file of this repository):

```
<class 'statsmodels.iolib.summary.Summary'>
"""
                        Unobserved Components Results                         
==============================================================================
Dep. Variable:                      y   No. Observations:                   70
Model:                    local level   Log Likelihood                 -22.952
Date:                Thu, 21 Feb 2019   AIC                             51.905
Time:                        17:36:58   BIC                             58.607
Sample:                             0   HQIC                            54.564
                                 - 70                                         
Covariance Type:                  opg                                         
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
sigma2.irregular     0.1054      0.022      4.776      0.000       0.062       0.149
sigma2.level         0.0001      0.001      0.212      0.832      -0.001       0.001
beta.X               0.9472      0.047     20.274      0.000       0.856       1.039
===================================================================================
Ljung-Box (Q):                       38.77   Jarque-Bera (JB):                 0.95
Prob(Q):                              0.53   Prob(JB):                         0.62
Heteroskedasticity (H):               1.15   Skew:                            -0.18
Prob(H) (two-sided):                  0.73   Kurtosis:                         2.55
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).
"""

```

There's all sorts of metrics that can be used for this purpose (even though they don't have a confidence interval they are still the most common methods used in statistics) such as `log likelihood`, `AIC`, `BIC`, `HQIC`.

Those values work in a relative manner; for AIC for instance, the lower the better.

There's also the statistical tests for the linear regression coefficients used in the fitting process. Here we can see that `sigma2.level` ended up being not much relevant (P>z = 0.832) whereas `irregular` and `X` are quite the opposite (P = 0).

Not quite sure if this was what you were looking for, please let me know if this helps you.

**Comment by yanirs** [comment]
Thanks @WillianFuks! Yeah, that's what I meant. I missed the option to access the `trained_model` summary.

**Comment by WillianFuks** [comment]
Glad to know it's what you were looking for :)!
