### ISSUE TITLE
Multivariate X

### ISSUE THREAD

**Issue by cchoirat** [dafiti/causalimpact#28]
In the example, `X` is univariate:
```python
X = 100 + arma_process.generate_sample(nsample=100)
y = 1.2 * X + np.random.normal(size=100)
```
Can it be multivariate?

Thanks!

**Comment by WillianFuks** [comment]
Hello @cchoirat ,

Sure, just did that. Could you please confirm if this is what you had in mind?

https://github.com/dafiti/causalimpact/blob/add_multivariateX/examples/getting_started.ipynb

I just added another `x` value to `X` to make it multivariate. As you can see, as far as coding goes, it's just the same :).

Let me know what you think,

Best,

Will

**Comment by cchoirat** [comment]
All set Will, thank you so much for your work!

**Comment by WillianFuks** [comment]
Glad to know this was what you were looking for :)

Any issues, just let us know.

Best Regards,

Will
