### ISSUE TITLE
Error with data range instead of int

### ISSUE THREAD

**Issue by franckdess** [dafiti/causalimpact#30]
Hi,

I'm trying to run the same code as the one you provided in the example with date range instead of int, as follow:

```
pre_period = ["2017-10-01 00:00:00", "2017-10-21 23:30:00"]
post_period = ["2017-10-22 00:00:00", "2017-10-31 23:30:00"]

ci = CausalImpact(dated_data, pre_period, post_period)
```

where the start and end period are in the index of my dataframe.

But when I run the code, I get the following error:

![Capture d’écran 2019-03-24 à 23 02 34](https://user-images.githubusercontent.com/25958951/54886511-f38af600-4e88-11e9-92ce-8078f4daf374.png)

Is there any way to fix it ?

Many thanks in advance,

Franck

**Comment by WillianFuks** [comment]
Hi @franckdess ,

Just wanted to confirm if you still have this issue. Is everything working for you now?

Thanks :)

Will

**Comment by franckdess** [comment]
Hi,

Thank you for contacting me. I found out the issue: I have multilevel index so when I reset the second level index (first level is the timestamp) I have many times the same timestamp which is confusing the pre and post periods.

Many thanks

Franck

Envoyé de mon iPhone

Le 25 mars 2019 à 12:35, Willian Fuks <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi @franckdess<https://github.com/franckdess> ,

Just wanted to confirm if you still have this issue. Is everything working for you now?

Thanks :)

Will
