### ISSUE TITLE
Summary message recommends the wrong command

### ISSUE THREAD

**Issue by joshtemple** [dafiti/causalimpact#33]
The last line in `ci.summary()` states:

```
For more details run the command: print(impact.summary('report'))
```

When I run the command `print(impact.summary('report'))`, I get this error:

```
NameError: name 'impact' is not defined
```

I believe the instructions should ask the user to run the command `print(ci.summary(output='report'))` instead.

**Comment by WillianFuks** [comment]
Hi @joshtemple ,

I see your point. I'll see if we can make the message better to understand.Thanks for reporting this!

**Comment by WillianFuks** [comment]
Hi @joshtemple ,

To avoid misinterpretations as you suggested, we added this example in the README file. We decided to not change the actual output text so to keep aligned with the Google's R package.

I'll close this issue for now, let us know if you think it still might be confusing :)

Best,

Will
