### ISSUE TITLE
Best way to print 'original' plot panel and hide the predicted line before the intervention

### ISSUE THREAD

**Issue by jdweaver** [dafiti/causalimpact#45]
I've been looking for a way to show the 'original' panel but mask the predicted line. I've found it causes some confusion when showing it to non-technical audience. 
I've tried printing out the CausalImpact.inferences but that doesn't seem to provide the data that generates the 'original' panel. 

Any tips or tricks would be great. 

thanks!

**Comment by WillianFuks** [comment]
Hi @jdweaver ,

We are happy to know the library is being useful for you :)!

If you find any other issues just let us know.

Best,

Will
