### ISSUE TITLE
Access to the data behind the plots 

### ISSUE THREAD

**Issue by kawssnoopy** [dafiti/causalimpact#55]
Is it possible to access to the data behind the plots as a dataframe?  I would like to publish the graphs on dashboard platform.

**Comment by kawssnoopy** [comment]
ci.inferences

**Comment by WillianFuks** [comment]
Hi @kawssnoopy ,

Looks like you have already figured this out. In `ci.inferences` you'll find all source data used for the plotting step, as a dataframe.

Let us know if you still have any issue :).

Best,

Will
