### ISSUE TITLE
Value range of the p-value is not [0, 1] but [0,0.5] ?

### ISSUE THREAD

**Issue by onysuke** [dafiti/causalimpact#77]
Hi, 

I think the posterior predictive p-value is calculated in the [_compute_p_value function](https://github.com/dafiti/causalimpact/blob/8d881fc5c270348d8c8ff59c936997a75d7c5fac/causalimpact/inferences.py#L425).

In the doc, it is stated that p_value can take values between 0 and 1. 
https://github.com/dafiti/causalimpact/blob/8d881fc5c270348d8c8ff59c936997a75d7c5fac/causalimpact/inferences.py#L444-L448

However, in the following expression, is it possible to have a maximum value of 1? 
```
signal = min(np.sum(sim_sum > y_post_sum), np.sum(sim_sum < y_post_sum))
return signal / (self.n_sims + 1)
```

If the doc has a typo, I would like to issue a PR to correct it. 
Please let me know if there is any mistake in my understanding. 
Thank you very much.

cc. @WillianFuks

**Comment by WillianFuks** [comment]
Hi @onysuke ,

It's not possible as the denominator is the total simulations plus one (`n_sims + 1`) whereas the denominator can be at most `n_sims`.

Still, it wouldn't be wrong a value p of 1 IIUC, that would mean that observing the counterfactual by chance is always possible (not a useful scenario in practice but still valid).

**Comment by onysuke** [comment]
Hi @WillianFuks,

Thanks for the thoughtful response. 
I understand about the denominator and that observing the counterfactual by chance is always possible.

When I did an experiment like the AA test with causalimpact, i.e., time series data where both outcome and covariates are non-intervention, I assumed a uniform distribution with p-values between 0 and 1 ([this link](https://www.microsoft.com/en-us/research/group/experimentation-platform-exp/articles/p-values-for-your-p-values-validating-metric-trustworthiness-by-simulated-a-a-tests/)), but I got a uniform distribution with values between 0 and 5 (Figure), which is why I asked the previous question.
![image](https://user-images.githubusercontent.com/23186686/120400192-643ad080-c378-11eb-890a-081f2f05ad3a.png)

`signal = min(np.sum(sim_sum > y_post_sum), np.sum(sim_sum < y_post_sum))`
I thought that since the minimum value is selected in this line, the p-value would not be in the range of 0 to 1, as it says in the [function description](https://github.com/dafiti/causalimpact/blob/8d881fc5c270348d8c8ff59c936997a75d7c5fac/causalimpact/inferences.py#L447), but in the range of 0 to 5 IIUC.

**Comment by onysuke** [comment]
Thanks for your explanation.

I was relieved to hear that I understood correctly. I understand that as follows; conceptually `p_value` can reach 1, but in this implementation, min operation keeps `p_value` up to 0.5.

We simulated various `y_posts` by randomly splitting the data in non-intervention areas into 50%:50% like A/A test.

Thanks.
